# Utiliser l'image officielle MySQL
FROM mysql:8.4.3

# Définir les variables d'environnement
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=cloud

# Copier le script SQL
COPY init.sql /docker-entrypoint-initdb.d/

# Exposer le port par défaut de MySQL
EXPOSE 3306
